# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidtipsoftheweek', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstaidtip',
            old_name='content',
            new_name='tip',
        ),
        migrations.AlterField(
            model_name='firstaidtip',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
