# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidtipsoftheweek', '0002_auto_20190819_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidtip',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='firstaidtip',
            name='post_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
