# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidtipsoftheweek', '0003_auto_20190822_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidtip',
            name='image',
        ),
    ]
