# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidtipsoftheweek', '0004_remove_firstaidtip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidtip',
            name='published_date',
        ),
        migrations.AddField(
            model_name='firstaidtip',
            name='enddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='firstaidtip',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
