# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstaidtipsoftheweek', '0006_auto_20190910_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidtip',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='firstaidtip',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
