# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adultsquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=250)),
                ('answer_a', models.CharField(default='', max_length=200)),
                ('answer_b', models.CharField(default='', max_length=200)),
                ('answer_c', models.CharField(default='', max_length=200)),
                ('answer_d', models.CharField(default='', max_length=200)),
                ('correct_answer', models.CharField(default='', max_length=1)),
                ('solution', models.TextField()),
            ],
        ),
    ]
