# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningforadults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultsquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='adultsquestion',
            name='question_id',
            field=models.CharField(default='', max_length=5),
        ),
    ]
