# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningforadults', '0002_auto_20190823_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adultsquestion',
        ),
    ]
