# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190731_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key='True', serialize=False),
        ),
    ]
