# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190827_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.CharField(default='', max_length=3),
        ),
    ]
