# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190827_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Courses'), ('K', 'Kits'), ('B', 'Books'), ('E', 'E-Books'), ('CD', 'CDs&DVDs'), ('M', 'Manikins'), ('X', 'Extras')], default='C', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
