# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190827_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Courses', 'Courses'), ('First Aid Kits', 'Kits'), ('Books', 'Books'), ('E-Books', 'E-Books'), ('CDs & DVDs', 'CDs&DVDs'), ('Manikins', 'Manikins'), ('Extras', 'Extras')], default='', max_length=250),
        ),
    ]
