# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190829_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_page',
            field=models.CharField(choices=[('N', 'No'), ('H', 'Home')], default='N', max_length=3),
        ),
    ]
