# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190831_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReviews',
            fields=[
                ('id', models.CharField(default='', max_length=20, primary_key='True', serialize=False)),
                ('rating', models.CharField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Ok'), ('2', 'Not Good'), ('1', 'Awful')], default='', max_length=20)),
                ('review', models.TextField()),
                ('user', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
