# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-31 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_postreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostReviews',
            new_name='PostReview',
        ),
    ]
