# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190831_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReview',
        ),
    ]
